### PR TITLE
Create code-of-conduct.md

### PR DESCRIPTION
**Pull request by traklord**
- Conversion and adaptation of Code of Conduct file located in Google Drive
- Created file in Docs

### CODE REVIEW

**Comment by yvettie86** [comment]
Line 31 - should "Crimea, Luhansk or Donetsk regions" be specified as parts of Ukraine? The other places listed are all countries.
Line 51 - should this be "Code" rather than "policy"?
Line 64 references a "harassment policy" - is that a different document, or should it be referring to this Code?

**Comment by hankish** [comment]
Responding to Yvette's notes here (on sync call with Ed):

> Line 31 - should "Crimea, Luhansk or Donetsk regions" be specified as parts of Ukraine? The other places listed are all countries.

Let's skip tweaking this language for now. The list doesn't claim to be comprehensive... and if we were to tweak this I would want legal counsel to do it.

> Line 51 - should this be "Code" rather than "policy"?

Good callout... Ed & my interpretation is that line 59 (which we're presuming is the one you were talking about) is referring specifically to the "policy" of Section A within the "code" of conduct. So it would stay as is.

> Line 64 references a "harassment policy" - is that a different document, or should it be referring to this Code?

Again, I think this is referring to the policy defined in this specific section of the code.

**Review by hankish — CHANGES_REQUESTED** [review]
Ed & I found some tweaks that still need to be done.

**Comment by TweedleUO** [comment]
incorporating feedback from this PR and creating a new one.

**Pull request closed without merging**
