### PR TITLE
Release 2

### PR DESCRIPTION
**Pull request by hankish**
# Gov Repo Release 2

## Release Notes

1. **Q-Git Flow:** We added an expedited approval process for contributions during development. This could likely continue to be improved, potentially by making the expedited process the default for now, since that's how it's likely to be used.

2. **Financial Model:** Version 2.1.0 updates:
  - Replaced the term "Fund" with the term "Ledger" throughout the document. This was needed in order to clarify that ledgers are an internal Quorum1 structure only and are not financial funds in a regulatory sense.
  - Created a `type` property on rev tokens to distinguish between time investment & money investment. Used this type property to tweak the rev token weighting algorithm for the org investment ledger in order to balance the payments between these two types. These changes have been long discussed and emerged from lots of iterative work. This work and the context is summarized in a separate section below (Explanation of Rev Token Type Updates). 
  - Small formatting changes (changing `<aside>` usage to [Github Markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts))
  - Fixed some broken links
  - A few small language tweaks

3. **Informal Governance Structure Definition & Roles:** This doc was changed to replace a problematic acronym. Non-substantive changes only.

4. **Process Note:** The first set of updates went a little outside of the process (we're still ironing out the kinks of the process).
  - There wasn't a formal pull request for the first set of changes. Instead we reviewed them as part of the initial partner review.
  - There's also a video walkthrough of the initial updates here: [2024-07-08 - Q1 Gov Repo - Release 2 - Initial Updates](https://drive.google.com/open?id=14toqOp2xz5vhQ3NG8qQ2VB-cO_weuu-x).

---

## Contribution Walkthrough Videos

* [2024-07-08 - Q1 Gov Repo - Release 2 - Initial Updates](https://drive.google.com/open?id=14toqOp2xz5vhQ3NG8qQ2VB-cO_weuu-x)
* [2024-07-10 - Q1 Gov Repo - Release 2 - Expedited Dev Approval](https://drive.google.com/file/d/14u7Zam9GBh7wLErwleSssJrLUdwRagSZ/view)

---

### Problem Recap

In the original structure, time investment and money investment are essentially paid out of the same bucket. As we modeled this out it became clear that this is deeply problematic because it means that:

1. Money investor payback schedule will vary based on our plans around time investment, making it almost impossible to easily model future returns
2. All of our “legacy rev tokens” (90%+ of which are for time investment) would greatly slow down the repayment of the money investors whom we are courting for the current investment round (and future rounds).
3. Because we are likely to always have more time investors than money investors, the money investors would always be at a huge disadvantage in repayment priority (with potentially up to 80% or more of rev token payments going to time investors).
4. Money investors would (fairly) see time investors as threats to their repayment. By decoupling these we remove this conflict and can actually balance the repayment schedule between both groups with the intention of parity & fairness.

By not distinguishing between money investment and time investment Rev Tokens we inadvertently created a large and unintended disparity in the payback schedule between the two constituencies. Rather than creating fairness, by not defining different Types of Rev Tokens we actually deprived ourselves of the ability to manage and balance the payback schedule. Not only would this create a zero sum game approach pitting money investors against time investors, but it would ironically create an issue where treating money and time investment “equally” would actually result in a permanent inequality, with much more of the repayment going to time investors. So by treating money investment rev tokens and time investment rev tokens equally we are, in essence, removing our own ability to establish and manage equality between the two very different types of investments.

And beyond those basic issues, this would also greatly complicate the documents needed in order to close the fundraising round, because we would have to disclose all of the legacy time investments and their justification as they would greatly impact investor repayment schedules. Why? Because we would need to disclose all of the legacy time investment and model the future time investment with a level of clarity that is challenging to achieve. It’s fairly straightforward to predict when we’re going to want to raise money and roughly how much (it may not be a perfect guess but it’s at least in the ballpark). It’s much more challenging to try and predict how much time investment compensation we’re going to need and what that may look like.

What we need is to be able to separate rev tokens into two groups: time rev tokens and money rev tokens. We need this in order to intelligently manage repayment between them in a more equitable and fair manner.

### Key Insights

* Money investors and time investors have different priorities. 
* Money investors have a greater need for predictability and modeling of returns.
* Money rev tokens and time rev tokens need to be categorized differently.
* We should seek to balance the percentages of gross revenues going to time investment and money investment.

### Summary of Related Changes

* We add “type” as a property of rev tokens with two possible values: Time or Money.
* We define a "Time-vs-Money Split Rate" (TVMSR) which determines the split between time and money rev tokens in each payment.
    * Goal: Maintain an average TVMSR of 50/50.
    * Adjustment: Can be changed based on the needs of the quorum but should not drop below 30% for either type.
* Org Investment Fund Design Guidelines
    * Guideline 2 - Rev Token Types & Cohorts
    * Guideline 3 - Allocation

### CODE REVIEW

**Comment by hankish** [comment]
We finalized this release on a call today. We did the initial partner review, made and approved some small changes, and then did the final partner review. 

## Call Participants

* Yvette: Voting for herself and Esteban
* Jay: Voting for himself and Jon
* Ed: Voting for himself and Stephanie
* Hank: Voting for himself, Prabhakar, and Trak

## Video Recording

[2024-07-10 - Partner Review - Gov Repo Release 2](https://drive.google.com/open?id=14xVs_Km_hQrd6fG5x8md7edjjacvRT6Z&usp=drive_fs)

**Review by JayKilian17 — APPROVED** [review]
Reviewed and Approved.

**Review by yvettie86 — APPROVED** [review]

**Review by edjieun — APPROVED** [review]
As per yesterday's I approve on behalf of myself and Stephanie.

**Comment by hankish** [comment]
Posting the screenshots from the slack voting thread here for transparency.

Slack Screenshot 2024-07-11 at 1 33 31 PM

**Comment by hankish** [comment]
**Official Vote Update:** We have 9 of 9 votes to approve. Vote passes.

Here is a summary of the approvals:
- Yvette: Voting for herself and Esteban
- Jay: Voting for himself and Jon
- Ed: Voting for himself and Stephanie
- Hank: Voting for himself, Prabhakar, and Trak

**Pull request merged**
