### PR TITLE
Release 3

### PR DESCRIPTION
**Pull request by hankish**
Potential future changes
- Update wiki.quorum.one/legal to point to gov repo instead
- Think through whether it's possible to remove "Workstream Wallets" specifically from the financial model and replace it with a more generic concept getting at the underlying goals without being so prescriptive.
- Consider adding an additional status for ledgers, particularly for investment ledgers, that is after Retired (or redefine Retired) such that once an investment ledger is empty of cash and has no active rev tokens it goes to a different status.

### CODE REVIEW

**Review by TweedleUO — APPROVED** [review]
As per the meeting I approve

**Comment by TweedleUO** [comment]
approving again after merge

**Review by traklord — APPROVED** [review]
I wholeheartedly approve

**Review by edjieun — APPROVED** [review]

**Comment by TweedleUO** [comment]
Release Notes:

* Moved the required fin ops content from financial model doc to new glossary doc. Didn't fix any links or anything so those are broken for now.

* Updated governance section of FM, changed it to Context of this Doc

* Incremented version of FM doc

* Moved structure out of FM doc and into its own doc. Updated opening section of FM doc to clarify this relationship.

* Updated title of key properties of a ledger section.

* Moved the entire 'Org Investment Ledger Design Guidelines' section out of the FM doc and into its own doc. For now nothing was changed, some linguistic and structural changes will come in a future commit.

* Investment ledger design + major repo refactor:
Big refactor of the gov repo structure in general and the financial model in particular, primarily in service of formally defining the org investment ledger.

**Pull request merged**
