### PR TITLE
Update igs-roles.md

### PR DESCRIPTION
**Pull request by traklord**
- rework Member Nomenclature
- add Strong Steward distinction

### CODE REVIEW

**Comment by yvettie86** [comment]
Line 45 makes reference to "unanimous approval of all Partners" - should this be "unanimous approval of all Stewards"?

**Review by hankish — APPROVED** [review]
Approved on sync call with Ed & Hank.

**Comment by edjieun** [comment]
Approve in synch meeting with Hank & Ed

**Comment by hankish** [comment]
Here's the recording of the review session with myself and @edjieun: [2024-11-13 - Gov Repo - Release 4 - Contribution Review Session](https://drive.google.com/file/d/1n-uJRfOTh1Dc8LNlAk0omq0Fo8AhKz01/view).

**Pull request merged**
